Repository misha1235000/SpikeClient, pull requests merged in 2019-08, with the labels that each got.

#88 Multiple hosts added
  src/app/auth/open-register-client/open-register-client.component.css
  src/app/auth/open-register-client/open-register-client.component.html
  src/app/auth/open-register-client/open-register-client.component.ts
  src/app/clients/client-host-uris/client-host-uris.component.css
  src/app/clients/client-host-uris/client-host-uris.component.html
  src/app/clients/client-host-uris/client-host-uris.component.ts
  src/app/clients/clients.component.css
  src/app/clients/clients.component.html
  src/app/clients/clients.component.ts
  src/app/clients/clients.service.ts
  src/app/toolbar/toolbar.component.css
  src/app/toolbar/toolbar.component.html
  src/assets/jpg/spike-logo.jpg
  src/assets/png/csvHelp.png
  src/assets/png/spike-logo - Copy.png
  src/assets/png/spike-logo.png
  src/favicon.ico
  src/index.html
  src/styles.css
Labels: feature

#89 Add feature of copying full hosturi, fixed bugs.
  src/app/clients/client-host-uris/client-host-uris.component.html
  src/app/clients/client-host-uris/client-host-uris.component.ts
  src/app/clients/clients.component.css
  src/app/clients/clients.component.html
Labels: feature, fix

#91 Update client-host-uris.component.css
  src/app/clients/client-host-uris/client-host-uris.component.css
Labels: fix
